name: CI

runs:
  push:
  pull_request:

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag=prebuilt-packages
    - run: mkdir -p packages && cd packages && docker export prebuilt-images | tar x
    - uses: actions/upload-artifacts@v1
      with:
        path: packages/**
        name: packages