name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cp .github/workflows/Dockerfile ./ && docker build --tag=prebuilt-packages .
    - run: mkdir -p packages && cd packages && docker export prebuilt-packages | tar x
    - uses: actions/upload-artifact@v1
      with:
        path: packages/**
        name: packages